-- MySQL Script generated by MySQL Workbench
-- Fri Jul 24 18:06:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dw_mt_manager
-- -----------------------------------------------------
-- 数据仓库元数据库

-- -----------------------------------------------------
-- Schema dw_mt_manager
--
-- 数据仓库元数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dw_mt_manager` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `dw_mt_manager` ;

-- -----------------------------------------------------
-- Table `dw_mt_manager`.`db_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_mt_manager`.`db_manager` (
  `db_id` INT NOT NULL AUTO_INCREMENT COMMENT '数仓库主键编号',
  `db_name` VARCHAR(45) NOT NULL COMMENT '库名称',
  `db_comment` VARCHAR(45) NULL COMMENT '注释',
  `db_access_type` INT NULL DEFAULT 1 COMMENT '数据源访问类型（1：JDBC   2：http   3：其他）',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `enable_flag` INT NULL DEFAULT 1 COMMENT '是否有效软删除标识（1：有效，0：无效）',
  PRIMARY KEY (`db_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_mt_manager`.`tb_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_mt_manager`.`tb_manager` (
  `tb_id` INT NOT NULL AUTO_INCREMENT COMMENT '数仓表主键编号',
  `tb_com_format` VARCHAR(45) NOT NULL COMMENT '存储压缩格式',
  `tb_name` VARCHAR(45) NOT NULL COMMENT '表名',
  `tb_comment` VARCHAR(45) NULL COMMENT '表备注',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `enable_flag` INT NULL DEFAULT 1 COMMENT '是否有效软删除标识（1：有效，0：无效）',
  `db_id` INT NOT NULL COMMENT '数据库主键编号',
  PRIMARY KEY (`tb_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_mt_manager`.`col_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_mt_manager`.`col_manager` (
  `col_id` INT NOT NULL AUTO_INCREMENT COMMENT '字段主键编号',
  `col_name` VARCHAR(45) NOT NULL COMMENT '字段名称',
  `col_type` VARCHAR(45) NOT NULL COMMENT '字段类型',
  `col_comment` VARCHAR(45) NULL COMMENT '字段注释',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `enable_flag` INT NULL DEFAULT 1 COMMENT '是否有效软删除标识（1：有效，0：无效）',
  `tb_id` INT NOT NULL COMMENT '数仓表主键编号',
  PRIMARY KEY (`col_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_mt_manager`.`task_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_mt_manager`.`task_manager` (
  `task_id` INT NOT NULL AUTO_INCREMENT COMMENT '任务主键ID',
  `task_type` INT NOT NULL COMMENT '任务类型（1：数据同步任务 2：ETL处理任务  3：数据导出任务）',
  `task_context` TEXT(5120) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `enable_flag` INT NULL DEFAULT 1 COMMENT '是否有效软删除标识（1：有效，0：无效）',
  `tb_id` INT NOT NULL,
  PRIMARY KEY (`task_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_mt_manager`.`db_param_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_mt_manager`.`db_param_manager` (
  `db_param_id` INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `db_param_name` VARCHAR(128) NOT NULL COMMENT '参数名称',
  `db_param_value` VARCHAR(128) NULL COMMENT '参数值',
  `db_param_comment` VARCHAR(512) NULL COMMENT '参数注释',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `enable_flag` INT NULL DEFAULT 1 COMMENT '是否有效软删除标识（1：有效，0：无效）',
  `db_id` INT NOT NULL,
  PRIMARY KEY (`db_param_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_mt_manager`.`sys_param_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_mt_manager`.`sys_param_manager` (
  `sys_param_id` INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `sys_param_name` VARCHAR(128) NOT NULL COMMENT '参数名称',
  `sys_param_value` VARCHAR(128) NULL COMMENT '参数值',
  `sys_param_comment` VARCHAR(45) NULL COMMENT '参数注释',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `enable_flag` INT NULL DEFAULT 1 COMMENT '是否有效软删除标识（1：有效，0：无效）',
  PRIMARY KEY (`sys_param_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
