package top.putop.mi.db.model;

import java.util.Date;

public class ColManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column col_manager.col_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Integer colId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column col_manager.col_name
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private String colName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column col_manager.col_type
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private String colType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column col_manager.col_comment
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private String colComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column col_manager.create_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column col_manager.update_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column col_manager.enable_flag
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Integer enableFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column col_manager.tb_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Integer tbId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column col_manager.col_id
     *
     * @return the value of col_manager.col_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Integer getColId() {
        return colId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column col_manager.col_id
     *
     * @param colId the value for col_manager.col_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setColId(Integer colId) {
        this.colId = colId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column col_manager.col_name
     *
     * @return the value of col_manager.col_name
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public String getColName() {
        return colName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column col_manager.col_name
     *
     * @param colName the value for col_manager.col_name
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setColName(String colName) {
        this.colName = colName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column col_manager.col_type
     *
     * @return the value of col_manager.col_type
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public String getColType() {
        return colType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column col_manager.col_type
     *
     * @param colType the value for col_manager.col_type
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setColType(String colType) {
        this.colType = colType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column col_manager.col_comment
     *
     * @return the value of col_manager.col_comment
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public String getColComment() {
        return colComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column col_manager.col_comment
     *
     * @param colComment the value for col_manager.col_comment
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setColComment(String colComment) {
        this.colComment = colComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column col_manager.create_time
     *
     * @return the value of col_manager.create_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column col_manager.create_time
     *
     * @param createTime the value for col_manager.create_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column col_manager.update_time
     *
     * @return the value of col_manager.update_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column col_manager.update_time
     *
     * @param updateTime the value for col_manager.update_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column col_manager.enable_flag
     *
     * @return the value of col_manager.enable_flag
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Integer getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column col_manager.enable_flag
     *
     * @param enableFlag the value for col_manager.enable_flag
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setEnableFlag(Integer enableFlag) {
        this.enableFlag = enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column col_manager.tb_id
     *
     * @return the value of col_manager.tb_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Integer getTbId() {
        return tbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column col_manager.tb_id
     *
     * @param tbId the value for col_manager.tb_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setTbId(Integer tbId) {
        this.tbId = tbId;
    }

    @Override
    public String toString() {
        return "ColManager{" +
                "colId=" + colId +
                ", colName='" + colName + '\'' +
                ", colType='" + colType + '\'' +
                ", colComment='" + colComment + '\'' +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                ", enableFlag=" + enableFlag +
                ", tbId=" + tbId +
                '}';
    }
}