package top.putop.mi.db.model;

import java.util.Date;

public class DbManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manager.db_id
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    private Integer dbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manager.db_name
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    private String dbName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manager.db_comment
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    private String dbComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manager.db_access_type
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    private Integer dbAccessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manager.create_time
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manager.update_time
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_manager.enable_flag
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    private Integer enableFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manager.db_id
     *
     * @return the value of db_manager.db_id
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    public Integer getDbId() {
        return dbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manager.db_id
     *
     * @param dbId the value for db_manager.db_id
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    public void setDbId(Integer dbId) {
        this.dbId = dbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manager.db_name
     *
     * @return the value of db_manager.db_name
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manager.db_name
     *
     * @param dbName the value for db_manager.db_name
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    public void setDbName(String dbName) {
        this.dbName = dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manager.db_comment
     *
     * @return the value of db_manager.db_comment
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    public String getDbComment() {
        return dbComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manager.db_comment
     *
     * @param dbComment the value for db_manager.db_comment
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    public void setDbComment(String dbComment) {
        this.dbComment = dbComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manager.db_access_type
     *
     * @return the value of db_manager.db_access_type
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    public Integer getDbAccessType() {
        return dbAccessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manager.db_access_type
     *
     * @param dbAccessType the value for db_manager.db_access_type
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    public void setDbAccessType(Integer dbAccessType) {
        this.dbAccessType = dbAccessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manager.create_time
     *
     * @return the value of db_manager.create_time
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manager.create_time
     *
     * @param createTime the value for db_manager.create_time
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manager.update_time
     *
     * @return the value of db_manager.update_time
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manager.update_time
     *
     * @param updateTime the value for db_manager.update_time
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_manager.enable_flag
     *
     * @return the value of db_manager.enable_flag
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    public Integer getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_manager.enable_flag
     *
     * @param enableFlag the value for db_manager.enable_flag
     *
     * @mbggenerated Fri Jul 24 18:10:02 CST 2020
     */
    public void setEnableFlag(Integer enableFlag) {
        this.enableFlag = enableFlag;
    }
}