package top.putop.mi.db.model;

import java.util.Date;

public class DbParamManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_param_manager.db_param_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Integer dbParamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_param_manager.db_param_name
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private String dbParamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_param_manager.db_param_value
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private String dbParamValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_param_manager.db_param_comment
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private String dbParamComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_param_manager.create_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_param_manager.update_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_param_manager.enable_flag
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Integer enableFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_param_manager.db_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Integer dbId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_param_manager.db_param_id
     *
     * @return the value of db_param_manager.db_param_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Integer getDbParamId() {
        return dbParamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_param_manager.db_param_id
     *
     * @param dbParamId the value for db_param_manager.db_param_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setDbParamId(Integer dbParamId) {
        this.dbParamId = dbParamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_param_manager.db_param_name
     *
     * @return the value of db_param_manager.db_param_name
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public String getDbParamName() {
        return dbParamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_param_manager.db_param_name
     *
     * @param dbParamName the value for db_param_manager.db_param_name
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setDbParamName(String dbParamName) {
        this.dbParamName = dbParamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_param_manager.db_param_value
     *
     * @return the value of db_param_manager.db_param_value
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public String getDbParamValue() {
        return dbParamValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_param_manager.db_param_value
     *
     * @param dbParamValue the value for db_param_manager.db_param_value
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setDbParamValue(String dbParamValue) {
        this.dbParamValue = dbParamValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_param_manager.db_param_comment
     *
     * @return the value of db_param_manager.db_param_comment
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public String getDbParamComment() {
        return dbParamComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_param_manager.db_param_comment
     *
     * @param dbParamComment the value for db_param_manager.db_param_comment
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setDbParamComment(String dbParamComment) {
        this.dbParamComment = dbParamComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_param_manager.create_time
     *
     * @return the value of db_param_manager.create_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_param_manager.create_time
     *
     * @param createTime the value for db_param_manager.create_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_param_manager.update_time
     *
     * @return the value of db_param_manager.update_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_param_manager.update_time
     *
     * @param updateTime the value for db_param_manager.update_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_param_manager.enable_flag
     *
     * @return the value of db_param_manager.enable_flag
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Integer getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_param_manager.enable_flag
     *
     * @param enableFlag the value for db_param_manager.enable_flag
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setEnableFlag(Integer enableFlag) {
        this.enableFlag = enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_param_manager.db_id
     *
     * @return the value of db_param_manager.db_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Integer getDbId() {
        return dbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_param_manager.db_id
     *
     * @param dbId the value for db_param_manager.db_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setDbId(Integer dbId) {
        this.dbId = dbId;
    }
}