package top.putop.mi.db.model;

import java.util.Date;

public class DwDbManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_db_manager.dw_db_id
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private Integer dwDbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_db_manager.db_name
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private String dbName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_db_manager.db_comment
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private String dbComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_db_manager.create_time
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_db_manager.update_time
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_db_manager.enable_flag
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private Integer enableFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_db_manager.dw_db_id
     *
     * @return the value of dw_db_manager.dw_db_id
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public Integer getDwDbId() {
        return dwDbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_db_manager.dw_db_id
     *
     * @param dwDbId the value for dw_db_manager.dw_db_id
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setDwDbId(Integer dwDbId) {
        this.dwDbId = dwDbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_db_manager.db_name
     *
     * @return the value of dw_db_manager.db_name
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_db_manager.db_name
     *
     * @param dbName the value for dw_db_manager.db_name
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setDbName(String dbName) {
        this.dbName = dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_db_manager.db_comment
     *
     * @return the value of dw_db_manager.db_comment
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public String getDbComment() {
        return dbComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_db_manager.db_comment
     *
     * @param dbComment the value for dw_db_manager.db_comment
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setDbComment(String dbComment) {
        this.dbComment = dbComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_db_manager.create_time
     *
     * @return the value of dw_db_manager.create_time
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_db_manager.create_time
     *
     * @param createTime the value for dw_db_manager.create_time
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_db_manager.update_time
     *
     * @return the value of dw_db_manager.update_time
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_db_manager.update_time
     *
     * @param updateTime the value for dw_db_manager.update_time
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_db_manager.enable_flag
     *
     * @return the value of dw_db_manager.enable_flag
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public Integer getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_db_manager.enable_flag
     *
     * @param enableFlag the value for dw_db_manager.enable_flag
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setEnableFlag(Integer enableFlag) {
        this.enableFlag = enableFlag;
    }
}