package top.putop.mi.db.model;

import java.util.Date;

public class SrcManager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column src_manager.src_id
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    private Integer srcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column src_manager.src_name
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    private String srcName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column src_manager.src_comment
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    private String srcComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column src_manager.src_access_type
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    private Integer srcAccessType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column src_manager.src_type
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    private Integer srcType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column src_manager.create_time
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column src_manager.update_time
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column src_manager.enable_flag
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    private Integer enableFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_manager.src_id
     *
     * @return the value of src_manager.src_id
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    public Integer getSrcId() {
        return srcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_manager.src_id
     *
     * @param srcId the value for src_manager.src_id
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    public void setSrcId(Integer srcId) {
        this.srcId = srcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_manager.src_name
     *
     * @return the value of src_manager.src_name
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    public String getSrcName() {
        return srcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_manager.src_name
     *
     * @param srcName the value for src_manager.src_name
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    public void setSrcName(String srcName) {
        this.srcName = srcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_manager.src_comment
     *
     * @return the value of src_manager.src_comment
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    public String getSrcComment() {
        return srcComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_manager.src_comment
     *
     * @param srcComment the value for src_manager.src_comment
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    public void setSrcComment(String srcComment) {
        this.srcComment = srcComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_manager.src_access_type
     *
     * @return the value of src_manager.src_access_type
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    public Integer getSrcAccessType() {
        return srcAccessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_manager.src_access_type
     *
     * @param srcAccessType the value for src_manager.src_access_type
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    public void setSrcAccessType(Integer srcAccessType) {
        this.srcAccessType = srcAccessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_manager.src_type
     *
     * @return the value of src_manager.src_type
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    public Integer getSrcType() {
        return srcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_manager.src_type
     *
     * @param srcType the value for src_manager.src_type
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    public void setSrcType(Integer srcType) {
        this.srcType = srcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_manager.create_time
     *
     * @return the value of src_manager.create_time
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_manager.create_time
     *
     * @param createTime the value for src_manager.create_time
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_manager.update_time
     *
     * @return the value of src_manager.update_time
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_manager.update_time
     *
     * @param updateTime the value for src_manager.update_time
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_manager.enable_flag
     *
     * @return the value of src_manager.enable_flag
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    public Integer getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_manager.enable_flag
     *
     * @param enableFlag the value for src_manager.enable_flag
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    public void setEnableFlag(Integer enableFlag) {
        this.enableFlag = enableFlag;
    }
}