package top.putop.mi.db.model;

import java.util.Date;

public class SrcParamManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column src_param_manager.src_param_id
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private Integer srcParamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column src_param_manager.src_param_name
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private String srcParamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column src_param_manager.src_param_value
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private String srcParamValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column src_param_manager.src_param_comment
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private String srcParamComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column src_param_manager.create_time
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column src_param_manager.update_time
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column src_param_manager.enable_flag
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private Integer enableFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column src_param_manager.src_id
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private Integer srcId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_param_manager.src_param_id
     *
     * @return the value of src_param_manager.src_param_id
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public Integer getSrcParamId() {
        return srcParamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_param_manager.src_param_id
     *
     * @param srcParamId the value for src_param_manager.src_param_id
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setSrcParamId(Integer srcParamId) {
        this.srcParamId = srcParamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_param_manager.src_param_name
     *
     * @return the value of src_param_manager.src_param_name
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public String getSrcParamName() {
        return srcParamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_param_manager.src_param_name
     *
     * @param srcParamName the value for src_param_manager.src_param_name
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setSrcParamName(String srcParamName) {
        this.srcParamName = srcParamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_param_manager.src_param_value
     *
     * @return the value of src_param_manager.src_param_value
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public String getSrcParamValue() {
        return srcParamValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_param_manager.src_param_value
     *
     * @param srcParamValue the value for src_param_manager.src_param_value
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setSrcParamValue(String srcParamValue) {
        this.srcParamValue = srcParamValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_param_manager.src_param_comment
     *
     * @return the value of src_param_manager.src_param_comment
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public String getSrcParamComment() {
        return srcParamComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_param_manager.src_param_comment
     *
     * @param srcParamComment the value for src_param_manager.src_param_comment
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setSrcParamComment(String srcParamComment) {
        this.srcParamComment = srcParamComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_param_manager.create_time
     *
     * @return the value of src_param_manager.create_time
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_param_manager.create_time
     *
     * @param createTime the value for src_param_manager.create_time
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_param_manager.update_time
     *
     * @return the value of src_param_manager.update_time
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_param_manager.update_time
     *
     * @param updateTime the value for src_param_manager.update_time
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_param_manager.enable_flag
     *
     * @return the value of src_param_manager.enable_flag
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public Integer getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_param_manager.enable_flag
     *
     * @param enableFlag the value for src_param_manager.enable_flag
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setEnableFlag(Integer enableFlag) {
        this.enableFlag = enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src_param_manager.src_id
     *
     * @return the value of src_param_manager.src_id
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public Integer getSrcId() {
        return srcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src_param_manager.src_id
     *
     * @param srcId the value for src_param_manager.src_id
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setSrcId(Integer srcId) {
        this.srcId = srcId;
    }
}