package top.putop.mi.db.model;

import java.util.Date;

public class SysParamManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param_manager.sys_param_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Integer sysParamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param_manager.sys_param_name
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private String sysParamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param_manager.sys_param_value
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private String sysParamValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param_manager.sys_param_comment
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private String sysParamComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param_manager.create_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param_manager.update_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param_manager.enable_flag
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Integer enableFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param_manager.sys_param_id
     *
     * @return the value of sys_param_manager.sys_param_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Integer getSysParamId() {
        return sysParamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param_manager.sys_param_id
     *
     * @param sysParamId the value for sys_param_manager.sys_param_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setSysParamId(Integer sysParamId) {
        this.sysParamId = sysParamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param_manager.sys_param_name
     *
     * @return the value of sys_param_manager.sys_param_name
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public String getSysParamName() {
        return sysParamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param_manager.sys_param_name
     *
     * @param sysParamName the value for sys_param_manager.sys_param_name
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setSysParamName(String sysParamName) {
        this.sysParamName = sysParamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param_manager.sys_param_value
     *
     * @return the value of sys_param_manager.sys_param_value
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public String getSysParamValue() {
        return sysParamValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param_manager.sys_param_value
     *
     * @param sysParamValue the value for sys_param_manager.sys_param_value
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setSysParamValue(String sysParamValue) {
        this.sysParamValue = sysParamValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param_manager.sys_param_comment
     *
     * @return the value of sys_param_manager.sys_param_comment
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public String getSysParamComment() {
        return sysParamComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param_manager.sys_param_comment
     *
     * @param sysParamComment the value for sys_param_manager.sys_param_comment
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setSysParamComment(String sysParamComment) {
        this.sysParamComment = sysParamComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param_manager.create_time
     *
     * @return the value of sys_param_manager.create_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param_manager.create_time
     *
     * @param createTime the value for sys_param_manager.create_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param_manager.update_time
     *
     * @return the value of sys_param_manager.update_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param_manager.update_time
     *
     * @param updateTime the value for sys_param_manager.update_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param_manager.enable_flag
     *
     * @return the value of sys_param_manager.enable_flag
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Integer getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param_manager.enable_flag
     *
     * @param enableFlag the value for sys_param_manager.enable_flag
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setEnableFlag(Integer enableFlag) {
        this.enableFlag = enableFlag;
    }
}