package top.putop.mi.db.model;

import java.util.Date;

public class TaskManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_manager.task_id
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_manager.task_type
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private Integer taskType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_manager.script_type
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private Integer scriptType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_manager.task_name
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_manager.task_comment
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private String taskComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_manager.create_time
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_manager.update_time
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_manager.enable_flag
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private Integer enableFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_manager.tb_id
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private Integer tbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_manager.src_id
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private Integer srcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_manager.task_context
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    private String taskContext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_manager.task_id
     *
     * @return the value of task_manager.task_id
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_manager.task_id
     *
     * @param taskId the value for task_manager.task_id
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_manager.task_type
     *
     * @return the value of task_manager.task_type
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_manager.task_type
     *
     * @param taskType the value for task_manager.task_type
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_manager.script_type
     *
     * @return the value of task_manager.script_type
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public Integer getScriptType() {
        return scriptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_manager.script_type
     *
     * @param scriptType the value for task_manager.script_type
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setScriptType(Integer scriptType) {
        this.scriptType = scriptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_manager.task_name
     *
     * @return the value of task_manager.task_name
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_manager.task_name
     *
     * @param taskName the value for task_manager.task_name
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_manager.task_comment
     *
     * @return the value of task_manager.task_comment
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public String getTaskComment() {
        return taskComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_manager.task_comment
     *
     * @param taskComment the value for task_manager.task_comment
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setTaskComment(String taskComment) {
        this.taskComment = taskComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_manager.create_time
     *
     * @return the value of task_manager.create_time
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_manager.create_time
     *
     * @param createTime the value for task_manager.create_time
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_manager.update_time
     *
     * @return the value of task_manager.update_time
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_manager.update_time
     *
     * @param updateTime the value for task_manager.update_time
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_manager.enable_flag
     *
     * @return the value of task_manager.enable_flag
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public Integer getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_manager.enable_flag
     *
     * @param enableFlag the value for task_manager.enable_flag
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setEnableFlag(Integer enableFlag) {
        this.enableFlag = enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_manager.tb_id
     *
     * @return the value of task_manager.tb_id
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public Integer getTbId() {
        return tbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_manager.tb_id
     *
     * @param tbId the value for task_manager.tb_id
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setTbId(Integer tbId) {
        this.tbId = tbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_manager.src_id
     *
     * @return the value of task_manager.src_id
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public Integer getSrcId() {
        return srcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_manager.src_id
     *
     * @param srcId the value for task_manager.src_id
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setSrcId(Integer srcId) {
        this.srcId = srcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_manager.task_context
     *
     * @return the value of task_manager.task_context
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public String getTaskContext() {
        return taskContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_manager.task_context
     *
     * @param taskContext the value for task_manager.task_context
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    public void setTaskContext(String taskContext) {
        this.taskContext = taskContext;
    }
}