package top.putop.mi.db.model;

import java.util.Date;

public class TbManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.tb_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Integer tbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.tb_com_format
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private String tbComFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.tb_name
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private String tbName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.tb_comment
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private String tbComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.create_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.update_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.enable_flag
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Integer enableFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.db_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    private Integer dbId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.tb_id
     *
     * @return the value of tb_manager.tb_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Integer getTbId() {
        return tbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.tb_id
     *
     * @param tbId the value for tb_manager.tb_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setTbId(Integer tbId) {
        this.tbId = tbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.tb_com_format
     *
     * @return the value of tb_manager.tb_com_format
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public String getTbComFormat() {
        return tbComFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.tb_com_format
     *
     * @param tbComFormat the value for tb_manager.tb_com_format
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setTbComFormat(String tbComFormat) {
        this.tbComFormat = tbComFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.tb_name
     *
     * @return the value of tb_manager.tb_name
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public String getTbName() {
        return tbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.tb_name
     *
     * @param tbName the value for tb_manager.tb_name
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setTbName(String tbName) {
        this.tbName = tbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.tb_comment
     *
     * @return the value of tb_manager.tb_comment
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public String getTbComment() {
        return tbComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.tb_comment
     *
     * @param tbComment the value for tb_manager.tb_comment
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setTbComment(String tbComment) {
        this.tbComment = tbComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.create_time
     *
     * @return the value of tb_manager.create_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.create_time
     *
     * @param createTime the value for tb_manager.create_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.update_time
     *
     * @return the value of tb_manager.update_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.update_time
     *
     * @param updateTime the value for tb_manager.update_time
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.enable_flag
     *
     * @return the value of tb_manager.enable_flag
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Integer getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.enable_flag
     *
     * @param enableFlag the value for tb_manager.enable_flag
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setEnableFlag(Integer enableFlag) {
        this.enableFlag = enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.db_id
     *
     * @return the value of tb_manager.db_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public Integer getDbId() {
        return dbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.db_id
     *
     * @param dbId the value for tb_manager.db_id
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    public void setDbId(Integer dbId) {
        this.dbId = dbId;
    }
}