package top.putop.mi.db.dao;

import top.putop.mi.db.model.ColManager;

import java.util.List;

public interface ColManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table col_manager
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    int deleteByPrimaryKey(Integer colId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table col_manager
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    int insert(ColManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table col_manager
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    int insertSelective(ColManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table col_manager
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    ColManager selectByPrimaryKey(Integer colId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table col_manager
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    int updateByPrimaryKeySelective(ColManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table col_manager
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    int updateByPrimaryKey(ColManager record);

    /**
     * 获取指定表的所有字段
     * @param tbId
     * @return
     */
    List<ColManager> selectByTbId(Integer tbId);
}