package top.putop.mi.db.dao;

import top.putop.mi.db.model.DbManager;

public interface DbManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_manager
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    int deleteByPrimaryKey(Integer dbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_manager
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    int insert(DbManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_manager
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    int insertSelective(DbManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_manager
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    DbManager selectByPrimaryKey(Integer dbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_manager
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    int updateByPrimaryKeySelective(DbManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_manager
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    int updateByPrimaryKey(DbManager record);
}