package top.putop.mi.db.dao;

import top.putop.mi.db.model.DbParamManager;

public interface DbParamManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_param_manager
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    int deleteByPrimaryKey(Integer dbParamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_param_manager
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    int insert(DbParamManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_param_manager
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    int insertSelective(DbParamManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_param_manager
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    DbParamManager selectByPrimaryKey(Integer dbParamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_param_manager
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    int updateByPrimaryKeySelective(DbParamManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_param_manager
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    int updateByPrimaryKey(DbParamManager record);
}