package top.putop.mi.db.dao;

import top.putop.mi.db.model.DwDbManager;

public interface DwDbManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dw_db_manager
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    int deleteByPrimaryKey(Integer dwDbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dw_db_manager
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    int insert(DwDbManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dw_db_manager
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    int insertSelective(DwDbManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dw_db_manager
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    DwDbManager selectByPrimaryKey(Integer dwDbId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dw_db_manager
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    int updateByPrimaryKeySelective(DwDbManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dw_db_manager
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    int updateByPrimaryKey(DwDbManager record);
}