package top.putop.mi.db.dao;

import top.putop.mi.db.model.SrcParamManager;

public interface SrcParamManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src_param_manager
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    int deleteByPrimaryKey(Integer srcParamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src_param_manager
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    int insert(SrcParamManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src_param_manager
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    int insertSelective(SrcParamManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src_param_manager
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    SrcParamManager selectByPrimaryKey(Integer srcParamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src_param_manager
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    int updateByPrimaryKeySelective(SrcParamManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src_param_manager
     *
     * @mbggenerated Mon Aug 17 16:44:18 CST 2020
     */
    int updateByPrimaryKey(SrcParamManager record);
}