package top.putop.mi.db.dao;

import top.putop.mi.db.model.ColManager;
import top.putop.mi.db.model.SrcParamManager;

import java.util.List;

public interface SrcParamManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src_param_manager
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    int deleteByPrimaryKey(Integer srcParamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src_param_manager
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    int insert(SrcParamManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src_param_manager
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    int insertSelective(SrcParamManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src_param_manager
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    SrcParamManager selectByPrimaryKey(Integer srcParamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src_param_manager
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    int updateByPrimaryKeySelective(SrcParamManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src_param_manager
     *
     * @mbg.generated Wed Aug 19 16:39:09 CST 2020
     */
    int updateByPrimaryKey(SrcParamManager record);

    /**
     * 获取指定数据源的所有环境参数
     * @param srcId
     * @return
     */
    List<SrcParamManager> selectByTbSrcId(Integer srcId);
}