package top.putop.mi.db.dao;

import top.putop.mi.db.model.SysParamManager;

public interface SysParamManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param_manager
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    int deleteByPrimaryKey(Integer sysParamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param_manager
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    int insert(SysParamManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param_manager
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    int insertSelective(SysParamManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param_manager
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    SysParamManager selectByPrimaryKey(Integer sysParamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param_manager
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    int updateByPrimaryKeySelective(SysParamManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_param_manager
     *
     * @mbggenerated Mon Jul 27 15:29:58 CST 2020
     */
    int updateByPrimaryKey(SysParamManager record);
}